### ISSUE TITLE
Do we want to include transformers in the installation instructions?

### ISSUE THREAD

**Issue by deniederhut** [ORNL/tx2#5]
If they are assumed to be the model source that gets used, it might make sense to include those in the README or as an optional requirement in setup.py.

**Comment by WildfireXIII** [comment]
I've updated the pip install line in the Examples section of the README to include the transformers package with a minimum version so the notebooks don't break. I'm hesitant to add it to the setup.py itself or the primary install lines because whether it's needed at all and what version is required is entirely dependent on the user's model implementation. TX2 by itself doesn't require huggingface, I just use it in my example notebooks for its convenience and popularity.
